name: 'Setup Cosmospolitan toolchain'
description:
  'GitHub action to setup Cosmospolitan toolchain on Linux, Windows and macOS.'

inputs:
  version:
    description: 'Cosmospolitan toolchain version'
    required: true
  path:
    description: 'Toolchain path'
    required: false
    default: '.cosmopolitan'

runs:
  using: 'node20'
  main: 'dist/index.js'
